name: tests

on:
  push:
    branches: [ v1 ]

env:
  DB_CONNECTION: sqlite
  DB_DATABASE: database/database.sqlite

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: '12'
          check-latest: true
      - name: ğŸ“‹ Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"
      - name: â• Create Database
        run: |
          mkdir -p database
          touch database/database.sqlite
      - name: ğŸ”¨ Build Application
        run: ./scripts/build.sh
      - name: ğŸ”‘ Generate keys
        run: php artisan key:generate
      - run: php artisan jwt:secret
      - name: ğŸ”“ Directory Permissions
        run: chmod -R 777 storage bootstrap/cache
      - name: ğŸƒ Execute tests (Unit and Feature tests) via PHPUnit
        run: vendor/bin/phpunit